# Generated by Django 4.0.1 on 2022-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('Sports_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sports_name', models.CharField(max_length=100)),
                ('no_of_player', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
