# Generated by Django 4.0.1 on 2022-02-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0003_rename_sports_id_sports_sports_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration_time', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ground_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.ground')),
                ('sports_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sports')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.user')),
            ],
        ),
    ]
