# Generated by Django 4.0.1 on 2022-02-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0006_alter_booking_booking_id_alter_ground_ground_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ground_id',
            new_name='ground',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sports_id',
            new_name='sports',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ground',
            old_name='sports_id',
            new_name='sports',
        ),
    ]
