# Generated by Django 4.0.1 on 2022-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0007_rename_ground_id_booking_ground_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
