# Generated by Django 4.0.1 on 2022-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0008_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sports',
            name='status',
        ),
    ]
