# Generated by Django 4.0.1 on 2022-03-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0009_player_remove_sports_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.user'),
        ),
    ]
