# Generated by Django 4.0.1 on 2022-03-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0010_remove_player_player_name_player_name_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
        migrations.AddField(
            model_name='player',
            name='sports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.sports'),
        ),
    ]
