# Generated by Django 4.0.1 on 2022-03-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0014_remove_team_player_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('classes_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField()),
                ('sports', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.sports')),
            ],
        ),
    ]
