# Generated by Django 4.0.1 on 2022-03-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0018_remove_tournament_date_remove_tournament_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sports.booking'),
        ),
    ]
