# Generated by Django 4.0.1 on 2022-03-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0019_alter_tournament_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.sports'),
        ),
    ]
