# Generated by Django 4.0.1 on 2022-03-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0020_team_sports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='sports_detail',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sports',
            new_name='sports_detail',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='sports',
            new_name='sports_detail',
        ),
        migrations.RenameField(
            model_name='ground',
            old_name='sports',
            new_name='sports_detail',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sports',
            new_name='sports_detail',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='sports',
            new_name='sports_detail',
        ),
    ]
