# Generated by Django 4.0.1 on 2022-03-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0022_rename_sports_detail_sports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.user'),
        ),
    ]
