# Generated by Django 4.0.1 on 2022-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0023_tournament_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
