# Generated by Django 4.0.1 on 2022-04-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0024_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
