# Generated by Django 4.0.1 on 2022-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0025_remove_booking_duration_time_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
