# Generated by Django 4.0.1 on 2022-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0026_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='per_hour_charge',
            field=models.IntegerField(default=200),
        ),
    ]
