# Generated by Django 4.0.1 on 2022-04-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0027_ground_per_hour_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accepted_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='Sports.user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='Sports.user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='Sports.team'),
        ),
    ]
