# Generated by Django 4.0.1 on 2022-04-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0028_tournament_accepted_user_alter_tournament_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.booking'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='Sports.team'),
        ),
    ]
