# Generated by Django 4.0.1 on 2022-04-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0029_alter_tournament_booking_alter_tournament_team_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sports.booking'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='Sports.team'),
        ),
    ]
