# Generated by Django 4.0.1 on 2022-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0030_alter_tournament_booking_alter_tournament_team_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sports.team'),
        ),
    ]
