# Generated by Django 4.0.1 on 2022-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0032_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='response',
            field=models.CharField(default='in waiting', max_length=100),
        ),
    ]
