# Generated by Django 4.0.1 on 2022-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0033_tournament_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_pass_token',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
