# Generated by Django 4.0.1 on 2022-04-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0038_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
