# Generated by Django 4.0.1 on 2022-04-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0042_payment_classes_payment_groung_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='groung',
        ),
        migrations.AddField(
            model_name='payment',
            name='ground_booning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sports.booking'),
        ),
    ]
