# Generated by Django 4.0.1 on 2022-04-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0044_rename_ground_booning_payment_ground_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ground_booking',
            new_name='booking',
        ),
    ]
