# Generated by Django 4.0.1 on 2022-04-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0045_rename_ground_booking_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='classes',
        ),
    ]
