# Generated by Django 4.0.1 on 2022-04-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0046_remove_payment_booking_remove_payment_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sports.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sports.classes'),
        ),
    ]
